### ISSUE TITLE
[m68k] register sp as register a7 alias 

### ISSUE THREAD

**Issue by hansbonini** [ARM9/bass#20]
Feature Suggest: `sp` as alias of register `a7`

**Comment by PeterLemon** [comment]
Hi hansbonini,

The way we handle alias of registers in the bass assembler is to use "constants" e.g you can place a "constant sp(a7)" in a general header include file to make this work. An example of this is in my MIPS header for N64 which you can find here: https://github.com/PeterLemon/N64/blob/master/LIB/N64.INC#L38-L68
I will now close this issue =D
