### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by ThatGuyJohnForbes** [ARM9/bass#28]
Compiling bass.cpp ...
bass.cpp:73:1: fatal error: opening dependency file obj/bass.d: No such file or directory
   73 | }
      | ^
compilation terminated.
make: *** [../nall/GNUmakefile:171: obj/bass.o] Error 1

**Comment by thar0x29a** [comment]
For everyone that runs into the same issue: you need to create an "obj" and "out" folder inside of "bass". 
Nasty git killed them again. I hope to add them soon.
