### ISSUE TITLE
did you mean std::data

### ISSUE THREAD

**Issue by jeffythedragonslayer** [ARM9/bass#31]
I have bass cloned but when I make I get errors; this is the first:

```
../nall/file.hpp: In static member function ‘static bool nall::file::exists(const nall::string&)’:
../nall/file.hpp:60:14: error: ‘data’ was not declared in this scope; did you mean ‘std::data’?
   60 |     return !(data.st_mode & S_IFDIR);
      |              ^~~~
      |              std::data

```

**Comment by meeq** [comment]
Looking at the relevant code here:
https://github.com/ARM9/bass/blob/4b808525131f7d69757121a4f50c8427ab30a405/nall/file.hpp#L51-L61

The only way this error would occur is if `API_POSIX` and `API_WINDOWS` were both not defined, which is an unsupported configuration.

What steps were used to perform the build, and under what operating system?

**Comment by jeffythedragonslayer** [comment]
I usually run make on windows from within cygwin, but perhaps that's behaving like some sort of limbo between posix and windows?

![image](https://user-images.githubusercontent.com/13253146/142295713-6eb7c9fe-9731-4f21-a548-ff3e8f2c33ac.png)

**Comment by meeq** [comment]
From https://cygwin.com/faq.html#faq.programming.preprocessor
> In gcc for Cygwin, `_WIN32` is only defined when you use the `-mwin32` gcc command line options. This is because Cygwin is supposed to be a POSIX emulation environment in the first place and defining `_WIN32` confuses some programs which think that they have to make special concessions for a Windows environment which Cygwin handles automatically.

**Comment by thar0x29a** [comment]
@meeq is right. I hope this solved the Issue for you. I was able to reproduce this issue by using cygwin. But right now im not certain if this will result into any changes, since I expect people to understand their development env, or download the compiled package.
