### ISSUE TITLE
Re-add "align" keyword

### ISSUE THREAD

**Issue by KungFuFurby** [ARM9/bass#32]
This keyword has been present in bass from the absolute earliest version up until v12r03, then it was removed. I'm currently not sure why, but it does restrict some programs to earlier versions of bass, most notably for me the SNESGSS sound driver.

**Comment by thar0x29a** [comment]
Under Nears/Byuus direction bass never cared about beeing compatible to anyone but him. Improvement > compatibility.

However this project, the official successor, will not handle it in this way. We will not change the syntax outside of mayor versions (everything below 20 counts as 1.** for us). And even then its very likely that the changes will hit the macro syntax and not the assembly endpoints. 

But v12 is really very, very old. Even LTS versions of Ubuntu ran out in that time. So I'm a bit confused about your post. In my (very personal and not project official) opinion people from them have many options to handle this issue:

1. Update the code. Really. Its been ages. If the project is still under development, you should update the code to bass18 std.. It marks the point when we will take it very serious how to act with you 'the user'. But for now were speaking about changes that had been done long before this fork has even been made.
2. Use the original v12 compiler for this certain asm file. They are still available in partner git repositories. But to be honest, patching the `align` stuff should be a no brainer. 

If you need help with point 1 just reach out for me. I would like to assist if any complicated stuff makes trouble.

**Comment by thar0x29a** [comment]
But dont get me wrong: To add an align - macro command is just a two-liner.
