### ISSUE TITLE
README file should mention what host platforms are supported/targeted for,

### ISSUE THREAD

**Issue by PeterCamilleri** [ARM9/bass#35]
Title says it all. I hate having to reverse engineer the code just to figure if I can run it.

**Comment by thar0x29a** [comment]
I agree. The point is that we have no one that looks deeper into our current arch files to give qualified feetback how "well" they perform after 4 updates in ther mayor version. 
But this info should be more "visible" - I agree.

**Comment by thar0x29a** [comment]
done. preview available on the devel branch
