### ISSUE TITLE
I Can't Join to the Discord

### ISSUE THREAD

**Issue by Vininess** [ARM9/bass#38]
Hi Guys, i try to enter on discord server but, after some minutes the server disappear

Thanks for the help

**Comment by thar0x29a** [comment]
Hm yeah I saw it. Dont know whats going on there. @Screwtapello - Any Idea? I saw other users having the same issue.
All I can offer right now is that you first add me manually first. Info is on my git profile.

**Comment by Vininess** [comment]
@thar0x29a hi, thanks for the reply

I will add you on discord
