### ISSUE TITLE
arch local constants

### ISSUE THREAD

**Issue by PeterLemon** [ARM9/bass#4]
This would be great for adding register names etc. to arch table files.

**Comment by thar0x29a** [comment]
That does not fit into our current compiling pipeline. I would reather think about having a set of libs included into our shipping, but do not bind them on the architecture itself.

Like not only having an 'architecture xyz' command but an 'system snes' command. 
This will not just setup the right architecture, but also load an given header file with all the constants you could think of. 

Edit: Well, im not happy with 'system' but maybe someone can come up with something better.

**Comment by qwertymodo** [comment]
This is kind of possible already via the use of namespaces.

**Comment by thar0x29a** [comment]
Yes it is. And I think thats how it should be done: on the lib-level, not on the architecture level.
