### ISSUE TITLE
Architecture Syntax

### ISSUE THREAD

**Issue by fraser125** [ARM9/bass#51]
I'm starting an architecture and while I'm reviewing the samples and reading the tables.cpp code to try and really figure it out. 
I'm really struggling with the reasons behind the MIPS syntax
`addi *05,*01,*08  ; %001000 >>04b >>03b >>02b >>01b ~b ~a >>08c ~c`
when I'm expecting something closer to 
`addi *05,*05,*16 ; %001000 ~b ~a ~c `
There are multiple questions here

1. Why is parameter 2 `*01` and not `*05`?
2. Why is parameter 3 `*08` and not `*16`? (Probably the same answer as above)
3. Why rebuild parameter `b` bit by bit? (Seems like the need for this might be a bug)
4. Why isn't `~b` inserting the same value again?
5. Why isn't `~c` inserting the same value again?
6. Why is the `c` being right shifted by 8 bits? 

I know the instruction works, when writing code and I've started on an architecture that is mostly 8 and 16 bit instructions and I haven't had any problems like this. Just when I think I've got this figured out I find this one instruction seems to have a bunch of weird things that break my understanding.
Thanks!

**Comment by fraser125** [comment]
So it seems that the *01 allows the rebuild of the b parameter. Otherwise there would be more bits written. (Each shift isn't discarding the upper bits, until the *01 is applied. So kind of a hack on the syntax. Still not sure why it needs to be rebuilt in the first place.

**Comment by PeterLemon** [comment]
The MIPS architecture in bass is built for big-endian MIPS instructions, bass would automatically encode the instruction bytes to little-endian order regardless of the big/little setting as this only affects data encoding for now. So the more hacky syntax I used forces the bytes to be encoded in big endian order.
