### ISSUE TITLE
N64.INC:5:1: constant r0(0) bass: assembly failed

### ISSUE THREAD

**Issue by deltakid0** [ARM9/bass#56]
I'm trying to assemble a test program from http://skelux.net/showthread.php?tid=331&pid=2452 and it simply fails with the message above, I downloaded the files N64.INC and N64_GFX.INC from Peter Lemon's Github.

Also, I tried to compile bass from the source code for Debian Stretch (32-bit) and it shows a lot of "nails" errors so I haven't been able to make any progress.

What am I doing wrong?

**Comment by PeterLemon** [comment]
Hi this source code was written for bass v14, so if you can get that to compile it should allow you to assemble this code.
If you have any problems assembling that code try assembling some pf the source code from my PeterLemon N64 GitHub source code, as that has been tested to assemble correctly with bass v14.

**Comment by deltakid0** [comment]
@PeterLemon thank you very much, I really appreciate your reply, I thought I was fated to be alone in this incredible trial that is writing code in MIPS asm.

You are correct, I didn't read entirely the description, it clearly says it is intended to be assembled with v14 bass assembler, I actually did something that most of the people would consider weird and compiled the assembler on 32-bit Debian Stretch and that assembled your code with no errors.

I'm looking for a very very basic piece of code that I can assemble and run on Project64 or any other emulator, the pink boot code in the skelux forum seemed to be simple but it doesn't work at all, I'm sorry if this is not the place to mention it but it turns out that I haven't been able to register, it simply allows you to fill in the info and at the moment of pushing the registration button it is simply disabled.

Thank you very much.

**Comment by PeterLemon** [comment]
No worries & good luck on you MIPS/N64 coding adventures, I am sure you will have lots of fun learning this great system =D
