### ISSUE TITLE
integrate new nall

### ISSUE THREAD

**Issue by PeterLemon** [ARM9/bass#6]
Need to integrate latest nall by byuu, used in his latest bass WIP.

**Comment by Tarek701** [comment]
Hello, PeterLemon.
The latest revision I could find only (with the help of WebArchive) was this one here:
https://web.archive.org/web/20140108065451/http://byuu.org/programming/nall/

I don't know if that was his latest one though. Pretty unlikely, I guess.

**Comment by Screwtapello** [comment]
For the forseeable future, the latest version of nall should be available for subtree/submodule importing at https://github.com/higan-emu/nall/

**Comment by thar0x29a** [comment]
We started working on v18. It will also include the latest nall version.
