### ISSUE TITLE
numeric literal bugs

### ISSUE THREAD

**Issue by PeterLemon** [ARM9/bass#9]
Numerical literal bug examples:
lda #$00            = A9 00
lda #$0000      = A9 00 00
lda #0          = A9 00 00
lda #00         = A9 00 00
lda #%00000000  = A9 00
lda #$0         = error: malformed expression
lda #$1         = error: malformed expression
lda #$01            = A9 01
lda #$001           = error: malformed expression

**Comment by jeffythedragonslayer** [comment]
A9 is the opcode for LDA with immediate addressing.  What's the bug here?  The "malformed expression" error could give more information, that's the biggest improvement I see that could be made.

https://undisbeliever.net/snesdev/65816-opcodes.html#lda-load-accumulator-from-memory

**Comment by PeterLemon** [comment]
I was basically trying to say that lda #0 should = A9 00 NOT A9 00 00
I have worked on this since & bass dev branch (v19) handles this correctly now.
Also lda #$001, lda #$0, lda #$1 works now without error.
The problem was that bass was not getting the correct bit length of numbers like that so defaulted to the longer word data amount when a number could have fit inside a byte data size. Can still force stuff with .b .w etc. in code anyway too.
